apiVersion: v1
kind: Pod
metadata:
  name: lookup-manifest-pod
spec:
  containers:
  - name: lookup-container 
    image: lookup
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
  - name: probe-container
    image: ubuntu
    command: sleep infinity