---
- hosts: vm1
  remote_user: centos
  tasks:
    #- name: galaxy k8s users install
    #  command: ansible-galaxy install cloud-pg.ansible_role_k8s_users
    #- name: galaxy condor install
    #  command: ansible-galaxy install cloud-pg.ansible_role_condor_client
    - name: install
      yum:
        name: https://github.com/indigo-dc/oidc-agent/releases/download/v3.2.7/oidc-agent-3.2.7-1.el7.x86_64.rpm
        state: present
    - name: install git 
      yum:
        name: git 
        state: present
    - name: get and unzip dodas client
      block:
        - name: unzip
          unarchive:
            src: https://github.com/Cloud-PG/dodas-go-client/releases/download/v0.2.2/dodas.zip
            dest: /usr/bin/
            remote_src: yes
        - name: permissions
          command: chmod 777 /usr/bin/dodas
      tags:
        - dodas_client
    - name: get dodas configuration
      copy:
        content: |
          cloud:
            id: os
            type: OpenStack
            host: https://cloud.recas.ba.infn.it:5000/v3
            username: indigo-dc
            password: user_token
            tenant: oidc
            service_region: recas-cloud
            auth_version: 3.x_oidc_access_token
          im:
            id: im
            type: InfrastructureManager
            host: https://im-dodas.cloud.cnaf.infn.it/infrastructures
            token: user_token
        dest: /home/centos/.dodas-template.yaml
      tags:
        - dodas_client
    - name: install kubectl
      get_url: 
        url: https://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl
        mode: 0777
    #- name: get install_helm
    #  get_url: 
    #   url: https://git.io/get_helm.sh
    #    dest: /usr/bin/get_helm
    #    mode: 0777
    #- name: install helm
    #  command: get_helm
    - name: install condor client
      include_role: 
        name: cloud-pg.ansible_role_condor_client
        #v2.0.0-dodas-rc7
      vars:
        iam:
          client_id: "dodas-demo"
          client_secret: "dodas-demo"
        tts:
          client_id: "CHANGEME"
          client_secret: "CHANGEME"
        admin:
          DN: "admin.DN"
        condor:
          host: "condor.host"
          schedd_name: "schedd_name"
      tags:
        - condor_client
    - name: install k8s client
      include_role: 
        name:  /home/dciangot/git/ansible-role-k8s_users
        #name: cloud-pg.ansible_role_k8s_users
      vars:
        users:
          path: "/home/centos/"
          prefix: user
          name: user01
        kube_admin:
          cluster: kubernetes
          cluster_url: https://.106:6443
          ca_oneline: CHANGEME 
          config: |
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority-data: CHANGEME 
                server: https://.106:6443
              name: kubernetes
            contexts:
            - context:
                cluster: kubernetes
                user: kubernetes-admin
              name: kubernetes-admin@kubernetes
            current-context: kubernetes-admin@kubernetes
            kind: Config
            preferences: {}
            users:
            - name: kubernetes-admin
              user:
                client-certificate-data: CHANGEME 
                client-key-data: CHANGEME 
          ca_cert_file: | 
            -----BEGIN CERTIFICATE-----
            -----END CERTIFICATE-----
          ca_cert_key: |
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
